apiVersion: v1
kind: Service
metadata:
  name: collector
  labels:
    app: collector
    service: collector
spec:
  ports:
    - port: 80
      name: http
  selector:
    app: collector
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: collector
  labels:
    app: collector
    version: v1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: collector
      version: v1
  template:
    metadata:
      labels:
        app: collector
        version: v1
    spec:
      containers:
        - name: collector
          image: tmtbe/mockest-collector:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80